# Generated by Django 5.0.7 on 2024-07-25 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_created_at_eventdata_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventComment',
            new_name='Comment',
        ),
    ]
